### ISSUE TITLE
The results are not as good as those shown in the paper

### ISSUE THREAD

**Issue by Gaozhongpai** [menpo/itwmm#9]
The notebook is very well documented and it is easy to reproduce the results. However, my reproduced results are not as good as those shown in the paper. 

**This is one face example.** 
![face](https://user-images.githubusercontent.com/4093624/55128849-0aaf3980-5150-11e9-8164-5973350f5e0f.png)
![land](https://user-images.githubusercontent.com/4093624/55128870-1bf84600-5150-11e9-9f79-b350b7e3320a.png)
![mash](https://user-images.githubusercontent.com/4093624/55128853-0daa2a00-5150-11e9-92c6-6a8b317a6160.png)

**This is another face example.** 
![Pai2](https://user-images.githubusercontent.com/4093624/55128354-3f21f600-514e-11e9-99ab-27e8364b3640.png) ![pai](https://user-images.githubusercontent.com/4093624/55128401-5fea4b80-514e-11e9-88cf-0acf16b399fd.png) ![paimesh](https://user-images.githubusercontent.com/4093624/55128428-7690a280-514e-11e9-8e76-ac94d2f2999e.png)

I didn't change any parameters in the notebook. I wonder if anyone reproduces the same results as the paper?

**Comment by wenpanli** [comment]
Hi, I noticed that you have run this code successfully, I wonder how to use my own image without iBUG 68 annotations? How can I achieve the iBUG 68 annotations on my own image? 
Thanks in advance!

**Comment by Gaozhongpai** [comment]
> Hi, I noticed that you have run this code successfully, I wonder how to use my own image without iBUG 68 annotations? How can I achieve the iBUG 68 annotations on my own image?
> Thanks in advance!

Hi, you can refer to this link: https://gist.github.com/patricksnape/0194fefb008462804470

**Comment by wenpanli** [comment]
The results are really not as good as those shown in the paper, I think there may be a difference in the parameter setting.

**Comment by qkgia** [comment]
@Gaozhongpai: Hi, do you use LSFM model with this code? I only use Basel Face Model to build ITWMM and then run image fitting. I got the error saying "operands could not be broadcast together with shapes (2,1,0) (0, 1000)" at line 56 jacobian.py
